export const GET_PRODUCTLIST_REQUESTED = 'GET_PRODUCTLIST_REQUESTED';
export const GET_PRODUCTLIST_SUCCSESS = 'GET_PRODUCTLIST_SUCCSESS';
export const GET_PRODUCTLIST_FAIL = 'GET_PRODUCTLIST_FAIL';


export const CREATE_PRODUCT_START = 'CREATE_PRODUCT_START';
export const CREATE_PRODUCT_SUCCSESS = 'CREATE_PRODUCT_SUCCSESS';
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL';
